micronaut:
  application:
    name: 'Micronaut 1.3.3'
---
datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
    jmx-enabled: true
    initial-size: 5
    max-active: 50
    min-idle: 5
    max-idle: 25
    max-wait-millis: 10000
    max-age: 600000
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
    validation-query: "SELECT 1"
    validation-query-timeout: 3
    validation-interval: 15000
    test-on-borrow: true
    test-while-idle: true
    test-on-return: false
    jdbc-interceptors: ConnectionState
jpa:
  default:
    packages-to-scan:
      - 'example.micronaut.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
---
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/db-changelog-master.xml'